/**
 * Created by Niko Osa on 9/5/16.
 */
enum FILTER {

    BASE_CURRENCY_CODE, TARGET_CURRENCY_CODE, CURRENCY_AMOUNT, BASE_CODE_INCORRECT, CURRENCY_AMOUNT_INCORRECT, TARGET_CODE_INCORRECT,
    SHOW_ALL_CURRENCY_CODES, CURRENCY_SELECTED, ANOTHER_CURRENCY_EXCHANGE, SAY_GOODBYE, INCORRECT_OPTION_SELECTED, REPEAT_ANOTHER_CURRENCY_EXCHANGE

}
